language: node_js
node_js:
  - "10"

cache: yarn

install:
  - yarn

script:
  - yarn run build
  - tar -zcvf dist.tar.gz dist/
  - echo uname -a

deploy:
  - provider: releases
    file_glob: true
    file: releases/*
    overwrite: true
    skip_cleanup: true
    api_key: "$GITHUB_API_TOKEN"
    on:
      tags: true
